#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


echo "\n\n"
echo "----------------------------------------"
echo "PRE-COMMIT HOOK RUNNING"
echo "----------------------------------------"
echo "RUNNING PRETTIER + ESLINT"

npx lint-staged --allow-empty

echo "\n\n"
echo "----------------------------------------"
echo "RUNNING TESTS"
echo "----------------------------------------"

# Uncomment this once test suite has been added to project
 npm run test
